name = "OptimalTransportEncoding"
uuid = "312e035e-a767-4ce3-8384-49b2c9cb5f83"
version = "0.1.0"
authors = ["Azamat Berdyshev <aberdysh@gmail.com>"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
cuPDLPx = "bcd6524d-1420-4b17-a582-359cb8a71a63"

[compat]
CUDA = "5.9.5"
CairoMakie = "0.15.8"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.11.0"
Serialization = "1.11.0"
Statistics = "1.11.1"
cuPDLPx = "0.1.4"
julia = "1.11.8, 1.12.3"
